# Generated by Django 2.2.5 on 2020-02-07 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mindtest',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_text', models.CharField(max_length=40)),
                ('test_info', models.CharField(max_length=100)),
                ('test_maxscore', models.IntegerField()),
            ],
            options={
                'db_table': 'mindest',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('q_text', models.CharField(max_length=200)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matteapp.Mindtest')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Qresult',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('res_text', models.CharField(max_length=100)),
                ('res_title', models.CharField(max_length=500)),
                ('res_div', models.IntegerField()),
                ('res_imglink', models.CharField(max_length=500)),
                ('res_videolink', models.CharField(max_length=500)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matteapp.Mindtest')),
            ],
            options={
                'db_table': 'qresult',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.TextField(blank=True, max_length=2)),
                ('age', models.IntegerField()),
                ('addr', models.CharField(blank=True, max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Mypage',
            fields=[
                ('mp_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_date', models.DateTimeField(verbose_name='date published')),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matteapp.Qresult')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matteapp.Mindtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mypage',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_val', models.IntegerField()),
                ('c_date', models.DateTimeField(verbose_name='date published')),
                ('q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matteapp.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'choice',
            },
        ),
    ]
